version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crewtest
      MYSQL_USER: admin
      MYSQL_PASSWORD: root      
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3306:3306